version: "3.8"

services:
  fastapi:
    build: ./backend
    volumes:
      - ./backend/main
    ports:
      - 5001:8000
    networks:
      - deploy_network

  streamlit:
    build: ./frontend
    volumes:
      - ./frontend/app
    ports:
      - "5000:8501"
    depends_on:
      - fastapi
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge